"""The frozen AMB harness installs under its own lock; only declared pins depart (#640)."""

from __future__ import annotations

import importlib.util
import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "amb_harness_constraints.py"
LANE = REPO_ROOT / "reference" / "agentmem_ref" / "evaluation" / "lanes" / "amb-precisionmembench-retrieval-v1.json"


def _load_script():
    spec = importlib.util.spec_from_file_location("amb_harness_constraints", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


EXPORT = """# This file was autogenerated by uv via the following command:
#    uv export --frozen --format requirements-txt --no-hashes --no-emit-project
backports-tarfile==1.2.0 ; python_full_version < '3.12'
    # via jaraco-context
cryptography==46.0.5
    # via
    #   authlib
    #   google-auth
jsonschema==4.26.0
Mem0AI==1.0.5
posthog==7.9.10
qdrant-client==1.17.0
torch==2.10.0
"""


class AmbHarnessConstraintsTests(unittest.TestCase):
    def setUp(self):
        self.module = _load_script()

    def test_repository_pins_are_read_from_pyproject_not_restated(self):
        pins = self.module.repository_pinned_packages()
        self.assertEqual(pins, ["jsonschema", "cryptography", "rfc8785"])

    def test_trim_keeps_every_locked_pin_except_the_declared_departures(self):
        kept, dropped = self.module.trim_constraints(
            EXPORT,
            drop={"cryptography": "repository pin", "mem0ai": "row pin", "posthog": "row pin lifts it", "rfc8785": "repository pin"},
        )
        self.assertEqual(
            kept,
            [
                "backports-tarfile==1.2.0 ; python_full_version < '3.12'",
                "jsonschema==4.26.0",
                "qdrant-client==1.17.0",
                "torch==2.10.0",
            ],
        )
        self.assertEqual(dropped, {"cryptography": "cryptography==46.0.5", "mem0ai": "Mem0AI==1.0.5", "posthog": "posthog==7.9.10"})
        self.assertNotIn("rfc8785", dropped, "a package the lock never carried is reported as absent, never invented")

    def test_trim_refuses_a_listing_that_is_not_exact_pins(self):
        with self.assertRaisesRegex(ValueError, "exact pins"):
            self.module.trim_constraints("qdrant-client>=1.13\n", drop={})
        with self.assertRaisesRegex(ValueError, "exact pins"):
            self.module.trim_constraints("-e ./amb\n", drop={})

    def test_row_pins_match_the_frozen_lane_and_bridge(self):
        import json

        sys.path.insert(0, str(REPO_ROOT / "reference"))
        try:
            import amb_mem0_explicit_bridge as bridge
        finally:
            sys.path.pop(0)
        row = self.module.ROW_PINS[bridge.AMB_PROVIDER_KEY]
        self.assertEqual(row["pins"], [f"mem0ai=={bridge.MEM0_VERSION}"])
        self.assertEqual(set(row["lift"]), {"mem0ai", "posthog"}, "only the pins mem0ai 2.2.1 contradicts are lifted")
        lane = json.loads(LANE.read_text(encoding="utf-8"))
        mem0_row = next(item for item in lane["systems"] if item["provider_key"] == bridge.AMB_PROVIDER_KEY)
        self.assertIn(row["pins"][0], mem0_row["dependency_pins"])
        lock = lane["execution"]["environment"]["harness_lock"]
        self.assertEqual(len(lock["git_blob"]), 40)
        self.assertEqual(len(lock["sha256"]), 64)
        self.assertTrue(any("posthog" in departure for departure in lock["departures"]))
        self.assertIn("uv.lock", lane["execution"]["environment"]["harness_install"])
        self.assertEqual(set(self.module.ROW_PINS), {bridge.AMB_PROVIDER_KEY}, "no other row departs from the lock")


if __name__ == "__main__":
    unittest.main()
