#!/usr/bin/env python3
"""Audit one #732 corpus-authoring subagent transcript (plan-732-generalization-gate G1).

The independent author may receive only the frozen prompts under
``reports/benchmarks/currentness-generalization/prompts/``. Their interpolations are mechanical:
``{AUTHOR_DIR}`` is the attempt directory, ``{CASE_IDS}`` is the output of
``select_metamorphic_bases.py`` and ``{REJECTIONS}`` is the output of
``check_generalization_corpus.py``. The author may call only ``Write`` and ``Read`` inside
``{AUTHOR_DIR}``, plus at most one ``SubagentHandback({"message": "done"})`` per pass.

A manifest names the attempt directory and the ordered coordinator messages:

    {"author_dir": "/abs/dir",
     "messages": [{"prompt": "variants", "value_file": "selection.json"},
                  {"prompt": "replace", "value_file": "rejections-r1.json"}]}

``value_file`` paths are relative to the manifest. Each holds the exact interpolated JSON text.

The rules are:

* (a) every assistant ``tool_use`` obeys the tool rule;
* (b) every ``type:"user"`` record is exactly one of:
  - (1) a ``tool_result``;
  - (2) a harness reminder: ``isMeta`` with no coordinator origin, whose whole content is
    ``<system-reminder>`` blocks;
  - (2b) the harness's output-limit continuation: ``isMeta`` with ``turnCompanion: true``, no
    origin, and content exactly ``CONTINUATION`` (amendment A1);
  - (3) a coordinator message equal to ``PREFIX + interpolated prompt + SUFFIX``, matching the
    manifest's order;
  - (4) the spawn record;
* (c) the first user record that is not a reminder is the interpolated ``spawn.txt``, as a
  plain string with no coordinator origin.

Advisory J1 applies. Each record must carry ``type`` and ``message.content``. A missing
``isMeta`` reads as false, and a missing ``origin`` means no coordinator origin. The audit fails
closed on an unknown content shape, an unknown ``origin.kind`` or an unknown record type.
Attachment records are generated by the harness, not by the orchestrator. They are counted
by type and reported.

The audit exits 1 on any violation. It has ``authority_effect: none``.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROMPTS = ROOT / "reports" / "benchmarks" / "currentness-generalization" / "prompts"
PREFIX = "The coordinator sent a message while you were working:\n"
SUFFIX = "\n\nAddress this before completing your current task."
CONTINUATION = (
    "Output token limit hit. Resume directly \u2014 no apology, no recap of what you were doing. "
    "Pick up mid-thought if that is where the cut happened. Break remaining work into smaller pieces."
)
REMINDER = re.compile(r"\s*(?:<system-reminder>.*?</system-reminder>\s*)+", re.DOTALL)
KNOWN_TYPES = {"user", "assistant", "attachment", "system"}
KNOWN_ORIGINS = {None, "coordinator"}
HANDBACK = "SubagentHandback"


def interpolate(name: str, author_dir: str, value: str | None = None) -> str:
    text = (PROMPTS / name).read_text(encoding="utf-8")
    text = text.replace("{AUTHOR_DIR}", author_dir)
    if value is not None:
        text = text.replace("{CASE_IDS}", value).replace("{REJECTIONS}", value)
    return text


def inside(path: str, author_dir: str) -> bool:
    if not isinstance(path, str) or not os.path.isabs(path) or ".." in Path(path).parts:
        return False
    real = os.path.realpath(path)
    base = os.path.realpath(author_dir)
    return real == base or real.startswith(base + os.sep)


def _content_kind(content) -> str | None:
    if isinstance(content, str):
        return "string"
    if isinstance(content, list) and content and all(isinstance(item, dict) for item in content):
        kinds = {item.get("type") for item in content}
        if kinds == {"tool_result"}:
            return "tool_result"
        if kinds == {"text"}:
            return "text"
    return None


def _text(content) -> str:
    if isinstance(content, str):
        return content
    return "".join(item.get("text", "") for item in content)


def audit(transcript: Path, manifest_path: Path) -> dict:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    author_dir = manifest["author_dir"]
    expected_messages = []
    for item in manifest.get("messages", []):
        name = {"variants": "variants.txt", "replace": "replace.txt"}[item["prompt"]]
        value = (manifest_path.parent / item["value_file"]).read_text(encoding="utf-8")
        expected_messages.append(PREFIX + interpolate(name, author_dir, value) + SUFFIX)
    spawn = interpolate("spawn.txt", author_dir)

    raw = transcript.read_bytes()
    records = [json.loads(line) for line in raw.decode("utf-8").splitlines() if line.strip()]
    violations: list[str] = []
    counts: Counter = Counter()
    attachments: Counter = Counter()
    seen_spawn = False
    next_message = 0
    handbacks_this_pass = 0

    for index, record in enumerate(records):
        rtype = record.get("type")
        if rtype not in KNOWN_TYPES:
            violations.append(f"record {index}: unknown record type {rtype!r}")
            continue
        if rtype == "attachment":
            attachments[(record.get("attachment") or {}).get("type")] += 1
            continue
        if rtype == "system":
            counts["system"] += 1
            continue
        message = record.get("message")
        if not isinstance(message, dict) or "content" not in message:
            violations.append(f"record {index}: missing message.content")
            continue
        content = message["content"]
        if rtype == "assistant":
            if isinstance(content, str):
                counts["assistant_text"] += 1
                continue
            if not isinstance(content, list):
                violations.append(f"record {index}: unknown assistant content shape")
                continue
            for item in content:
                if not isinstance(item, dict):
                    violations.append(f"record {index}: unknown assistant content item")
                    continue
                if item.get("type") != "tool_use":
                    continue
                name, tool_input = item.get("name"), item.get("input")
                counts[f"tool_use:{name}"] += 1
                if name in {"Write", "Read"}:
                    if not isinstance(tool_input, dict) or not inside(tool_input.get("file_path"), author_dir):
                        violations.append(f"record {index}: {name} outside author_dir")
                elif name == HANDBACK:
                    handbacks_this_pass += 1
                    if tool_input != {"message": "done"}:
                        violations.append(f"record {index}: hand-back input is not {{'message': 'done'}}")
                    if handbacks_this_pass > 1:
                        violations.append(f"record {index}: more than one hand-back in a pass")
                else:
                    violations.append(f"record {index}: forbidden tool {name!r}")
            continue

        # type == "user"
        origin = record.get("origin")
        origin_kind = origin.get("kind") if isinstance(origin, dict) else None
        if origin is not None and not isinstance(origin, dict):
            violations.append(f"record {index}: unknown origin shape")
            continue
        if origin_kind not in KNOWN_ORIGINS:
            violations.append(f"record {index}: unknown origin.kind {origin_kind!r}")
            continue
        kind = _content_kind(content)
        if kind is None:
            violations.append(f"record {index}: unknown user content shape")
            continue
        is_meta = bool(record.get("isMeta", False))
        if kind == "tool_result" and origin_kind is None:
            counts["tool_result"] += 1
            continue
        text = _text(content)
        if is_meta and origin_kind is None and REMINDER.fullmatch(text):
            counts["reminder"] += 1
            continue
        if is_meta and origin_kind is None and record.get("turnCompanion") is True and text == CONTINUATION:
            counts["continuation"] += 1
            continue
        if not seen_spawn:
            if origin_kind is None and kind == "string" and text == spawn:
                seen_spawn = True
                counts["spawn"] += 1
                continue
            violations.append(f"record {index}: first non-reminder user record is not the interpolated spawn.txt")
            seen_spawn = True
            continue
        if origin_kind == "coordinator":
            if next_message < len(expected_messages) and text == expected_messages[next_message]:
                next_message += 1
                handbacks_this_pass = 0
                counts["coordinator"] += 1
                continue
            violations.append(f"record {index}: coordinator message does not match frozen prompt #{next_message + 1}")
            continue
        violations.append(f"record {index}: unclassified user record")

    if not seen_spawn:
        violations.append("no spawn record")
    if next_message != len(expected_messages):
        violations.append(f"{len(expected_messages) - next_message} manifest message(s) never delivered")
    return {
        "transcript": str(transcript),
        "transcript_sha256": hashlib.sha256(raw).hexdigest(),
        "author_dir": author_dir,
        "prompt_sha256": {
            name: hashlib.sha256((PROMPTS / name).read_bytes()).hexdigest()
            for name in ("brief.md", "spawn.txt", "variants.txt", "replace.txt")
        },
        "records": len(records),
        "counts": dict(sorted(counts.items())),
        "attachment_types": dict(sorted((str(k), v) for k, v in attachments.items())),
        "violations": violations,
        "verdict": "PASS" if not violations else "INVALID",
        "authority_effect": "none",
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("transcript", type=Path)
    parser.add_argument("manifest", type=Path)
    parser.add_argument("--out", type=Path)
    args = parser.parse_args(argv)
    result = audit(args.transcript, args.manifest)
    text = json.dumps(result, indent=2, sort_keys=True) + "\n"
    if args.out:
        args.out.write_text(text, encoding="utf-8")
    sys.stdout.write(text)
    return 0 if result["verdict"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
