#!/usr/bin/env python3
"""Render/check Runtime Baseline v1 from the machine-readable source (#638)."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "reports" / "runtime" / "baseline-v1.json"
OUTPUT = ROOT / "reports" / "runtime" / "baseline-v1.md"


def render(data: dict) -> str:
    identity = data["identity"]
    ranking = identity["ranking"]
    persistence = data["persistence_and_durability"]
    evidence = data["qualification_evidence"]
    dogfood = data["dogfood"]
    lines = [
        "# Agent Memory Runtime Baseline v1",
        "",
        "> Generated from `reports/runtime/baseline-v1.json`. Do not edit this file by hand.",
        "",
        f"- **Status:** `{data['status']}`",
        f"- **Runtime revision:** `{data['runtime_revision']['commit']}`",
        f"- **Runtime:** `{identity['runtime_id']}` `{identity['runtime_version']}`",
        f"- **Profile:** `{identity['runtime_profile_id']}` `{identity['runtime_profile_version']}`",
        f"- **Public contract:** `{identity['public_contract_version']}`",
        f"- **Ranking policy:** `{ranking['active_policy_version']}`",
        f"- **Production 1.0:** `{str(data['production_1_0']).lower()}`",
        "",
        "## Public runtime contract",
        "",
        "Lifecycle: " + ", ".join(f"`{x}`" for x in data["public_runtime_contract"]["lifecycle"]) + ".",
        "",
        "Inspection/governance: " + ", ".join(f"`{x}`" for x in data["public_runtime_contract"]["inspection_and_governance"]) + ".",
        "",
        "## Persistence and durability",
        "",
        f"Canonical store is {persistence['canonical_store']} under `{identity['sqlite_substrate_profile']}` / schema `{identity['sqlite_substrate_schema_version']}`. "
        f"Active commitments are `{persistence['canonical_state_commitment']['active_scheme']}` for canonical state and `{persistence['governance_state_commitment']['active_scheme']}` for governance state. "
        "The qualified runtime is single-host; distributed/multi-host persistence is unsupported.",
        "",
        "Canonical JSON v2 is an accepted migration candidate under ADR-040, not the active commitment scheme.",
        "",
        "## Write semantics",
        "",
        f"Write interpretation is `{identity['write_semantics_interpreter']['ref']}` `{identity['write_semantics_interpreter']['version']}`. "
        "It emits evidence for proposition identity, cardinality, principal-proposition temporal aspect, bounded self-validity, markers, and same-slot relations. Interpretation has no authority effect and proposals are never auto-applied.",
        "",
        "## Read and ranking semantics",
        "",
        f"Query temporal interpretation is `{identity['query_temporal_interpreter']['ref']}` `{identity['query_temporal_interpreter']['version']}`. "
        f"Candidate routes are {', '.join(f'`{x}`' for x in data['read_semantics']['candidate_routes'])}. All candidates cross one governed admission boundary before ranking.",
        "",
        f"Policy `{ranking['active_policy_version']}` wraps lexical/base policy `{ranking['base_lexical_policy_version']}`. "
        f"Its unknown-basis profile is `{ranking['unknown_basis_policy']}` and the lexical anti-laundering guard is `{ranking['lexical_anti_laundering_guard']}`.",
        "",
        "## Native capability inventory",
        "",
    ]
    for name, status in data["capabilities"].items():
        lines.append(f"- `{name}`: `{status}`")
    lines += ["", "## Governance invariants", ""]
    for invariant in data["governance_invariants"]:
        lines.append(f"- `{invariant}`")
    lines += [
        "",
        "## Qualification evidence",
        "",
        f"- AgentMemBench exact-source recall@5: **{evidence['agentmembench']['exact_source_recall_at_5']:.3f}**",
        f"- LongMemEval_S session recall_all@5: **{evidence['longmemeval_s']['session_recall_all_at_5']:.6f}**",
        f"- LongMemEval_S turn recall_all@10: **{evidence['longmemeval_s']['turn_recall_all_at_10']:.3f}**",
        f"- LongMemEval_M session recall_all@5: **{evidence['longmemeval_m']['session_recall_all_at_5']:.6f}**",
        f"- LongMemEval_M turn recall_all@5: **{evidence['longmemeval_m']['turn_recall_all_at_5']:.5f}**",
        f"- #594 Part R known precision / recall: **{evidence['natural_semantics_594']['part_r_known_precision']:.3f} / {evidence['natural_semantics_594']['part_r_known_recall']:.6f}**",
        f"- #591 search p50 / p95: **{evidence['performance_591']['search_p50_ms']} / {evidence['performance_591']['search_p95_ms']} ms**",
        f"- Same-harness non-Agent-Memory systems accepted at freeze: **{evidence['same_harness_competitors']['accepted_non_agent_memory_systems']}** (`{evidence['same_harness_competitors']['status']}`)",
        "",
        "## Known limitations",
        "",
    ]
    for item in data["known_limitations"]:
        issue = f" (#{item['issue']})" if "issue" in item else ""
        lines.append(f"- **{item['id']}**{issue}: `{item['status']}`. {item.get('evidence', '')}".rstrip())
    lines += [
        "",
        "## Completion boundary",
        "",
    ]
    if dogfood["status"] == "completed":
        lines.append(
            f"Public Gauntlet dogfood through #{dogfood['public_gauntlet_issue']} is `completed` and evidence-bound to PR #{dogfood['merge_pr']} / merge commit `{dogfood['merge_commit']}`. The #638 close gate is satisfied."
        )
    else:
        lines.append(
            f"Public Gauntlet dogfood through #{dogfood['public_gauntlet_issue']} remains `{dogfood['status']}` and is required before #638 closes."
        )
    lines += [
        "",
        "This baseline is an immutable RC1 runtime target, not a production 1.0 declaration and not permission to treat benchmark score, ranking, interpretation, or external verification as memory authority.",
        "",
    ]
    return "\n".join(lines)


def validate(data: dict) -> None:
    required = {"schema_version", "baseline_id", "runtime_revision", "identity", "public_runtime_contract", "persistence_and_durability", "write_semantics", "read_semantics", "capabilities", "governance_invariants", "qualification_evidence", "known_limitations", "dogfood", "drift_policy"}
    missing = required - set(data)
    if missing:
        raise SystemExit(f"baseline manifest missing required keys: {sorted(missing)}")
    commit = data["runtime_revision"]["commit"]
    if len(commit) != 40 or any(ch not in "0123456789abcdef" for ch in commit):
        raise SystemExit("runtime_revision.commit must be an exact lowercase 40-hex SHA")
    if data["production_1_0"]:
        raise SystemExit("Runtime Baseline v1 must not claim production 1.0")
    if data["authority_effect"] != "none":
        raise SystemExit("baseline authority_effect must remain none")
    if data["dogfood"]["required_before_issue_638_close"] is not True:
        raise SystemExit("public Gauntlet dogfood must remain a close gate")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    validate(data)
    rendered = render(data)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            raise SystemExit("runtime baseline Markdown drifted; run scripts/render_runtime_baseline.py")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
