#!/usr/bin/env python3
"""Render/check every registered Runtime Baseline from its machine-readable record (#638, #674)."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from check_runtime_baseline_equivalence import (  # noqa: E402
    DEFAULT_REGISTER,
    load_register,
    qualification_block,
)

ROOT = Path(__file__).resolve().parents[1]


def baseline_label(baseline_id: str) -> str:
    match = re.fullmatch(r"agent-memory-runtime-baseline-(v[0-9]+)", baseline_id)
    if not match:
        raise SystemExit(f"baseline_id {baseline_id!r} does not name a numbered Runtime Baseline")
    return match.group(1)


def render(data: dict, public_gauntlet: dict, record_path: str) -> str:
    identity = data["identity"]
    ranking = identity["ranking"]
    persistence = data["persistence_and_durability"]
    evidence = data["qualification_evidence"]
    dogfood = data["dogfood"]
    label = baseline_label(data["baseline_id"])
    baseline_issue = data["runtime_revision"]["baseline_issue"]
    lines = [
        f"# Agent Memory Runtime Baseline {label}",
        "",
        f"> Generated from `{record_path}`. Do not edit this file by hand.",
        "",
        f"- **Status:** `{data['status']}`",
        f"- **Runtime revision:** `{data['runtime_revision']['commit']}`",
        f"- **Runtime:** `{identity['runtime_id']}` `{identity['runtime_version']}`",
        f"- **Profile:** `{identity['runtime_profile_id']}` `{identity['runtime_profile_version']}`",
        f"- **Public contract:** `{identity['public_contract_version']}`",
        f"- **Ranking policy:** `{ranking['active_policy_version']}`",
        f"- **Production 1.0:** `{str(data['production_1_0']).lower()}`",
        "",
        "## Public runtime contract",
        "",
        "Lifecycle: " + ", ".join(f"`{x}`" for x in data["public_runtime_contract"]["lifecycle"]) + ".",
        "",
        "Inspection/governance: " + ", ".join(f"`{x}`" for x in data["public_runtime_contract"]["inspection_and_governance"]) + ".",
        "",
        "## Persistence and durability",
        "",
        f"Canonical store is {persistence['canonical_store']} under `{identity['sqlite_substrate_profile']}` / schema `{identity['sqlite_substrate_schema_version']}`. "
        f"Active commitments are `{persistence['canonical_state_commitment']['active_scheme']}` for canonical state and `{persistence['governance_state_commitment']['active_scheme']}` for governance state. "
        "The qualified runtime is single-host; distributed/multi-host persistence is unsupported.",
        "",
        "Canonical JSON v2 is an accepted migration candidate under ADR-040, not the active commitment scheme.",
        "",
        "## Write semantics",
        "",
        f"Write interpretation is `{identity['write_semantics_interpreter']['ref']}` `{identity['write_semantics_interpreter']['version']}`. "
        "It emits evidence for proposition identity, cardinality, principal-proposition temporal aspect, bounded self-validity, markers, and same-slot relations. Interpretation has no authority effect and proposals are never auto-applied.",
        "",
        "## Read and ranking semantics",
        "",
        f"Query temporal interpretation is `{identity['query_temporal_interpreter']['ref']}` `{identity['query_temporal_interpreter']['version']}`. "
        f"Candidate routes are {', '.join(f'`{x}`' for x in data['read_semantics']['candidate_routes'])}. All candidates cross one governed admission boundary before ranking.",
        "",
        f"Policy `{ranking['active_policy_version']}` wraps lexical/base policy `{ranking['base_lexical_policy_version']}`. "
        f"Its unknown-basis profile is `{ranking['unknown_basis_policy']}` and the lexical anti-laundering guard is `{ranking['lexical_anti_laundering_guard']}`.",
        "",
        "## Native capability inventory",
        "",
    ]
    for name, status in data["capabilities"].items():
        lines.append(f"- `{name}`: `{status}`")
    lines += ["", "## Governance invariants", ""]
    for invariant in data["governance_invariants"]:
        lines.append(f"- `{invariant}`")
    lines += [
        "",
        "## Qualification evidence",
        "",
        f"- AgentMemBench exact-source recall@5: **{evidence['agentmembench']['exact_source_recall_at_5']:.3f}**",
        f"- LongMemEval_S session recall_all@5: **{evidence['longmemeval_s']['session_recall_all_at_5']:.6f}**",
        f"- LongMemEval_S turn recall_all@10: **{evidence['longmemeval_s']['turn_recall_all_at_10']:.3f}**",
        f"- LongMemEval_M session recall_all@5: **{evidence['longmemeval_m']['session_recall_all_at_5']:.6f}**",
        f"- LongMemEval_M turn recall_all@5: **{evidence['longmemeval_m']['turn_recall_all_at_5']:.5f}**",
        f"- #594 Part R known precision / recall: **{evidence['natural_semantics_594']['part_r_known_precision']:.3f} / {evidence['natural_semantics_594']['part_r_known_recall']:.6f}**",
        f"- #591 search p50 / p95: **{evidence['performance_591']['search_p50_ms']} / {evidence['performance_591']['search_p95_ms']} ms**",
        f"- Same-harness non-Agent-Memory systems accepted at freeze: **{evidence['same_harness_competitors']['accepted_non_agent_memory_systems']}** (`{evidence['same_harness_competitors']['status']}`)",
        (
            f"- Runtime Baseline public Gauntlet path: **{public_gauntlet['status']}** via `{public_gauntlet['transport']}` at head `{public_gauntlet['verified_head']}`; artifact `{public_gauntlet['artifact_digest']}`; probe exact-top1 **{public_gauntlet['exact_top1']:.1f}** (`baseline_or_probe`, not efficacy evidence)"
            if public_gauntlet["status"] == "complete"
            else f"- Runtime Baseline public Gauntlet path: **pending** via `{public_gauntlet['transport']}` (`baseline_or_probe`, not efficacy evidence)"
        ),
        "",
        "## Known limitations",
        "",
    ]
    for item in data["known_limitations"]:
        issue = f" (#{item['issue']})" if "issue" in item else ""
        lines.append(f"- **{item['id']}**{issue}: `{item['status']}`. {item.get('evidence', '')}".rstrip())
    lines += [
        "",
        "## Completion boundary",
        "",
    ]
    if dogfood["status"] == "completed" and public_gauntlet["status"] == "complete":
        lines.append(
            f"Public Gauntlet dogfood through #{dogfood['public_gauntlet_issue']} is `completed` and evidence-bound to PR #{dogfood['merge_pr']} / merge commit `{dogfood['merge_commit']}`. Runtime Baseline {label} itself also completed the public stdio contestant path in workflow `{public_gauntlet['workflow_run']}`. The #{baseline_issue} close gate is satisfied."
        )
    else:
        lines.append(
            f"Public Gauntlet dogfood through #{dogfood['public_gauntlet_issue']} is `{dogfood['status']}` and Runtime Baseline public qualification is `{public_gauntlet['status']}`; both are required before #{baseline_issue} closes."
        )
    lines += [
        "",
        "This baseline is an immutable RC1 runtime target, not a production 1.0 declaration and not permission to treat benchmark score, ranking, interpretation, or external verification as memory authority.",
        "",
    ]
    return "\n".join(lines)


def validate(data: dict) -> None:
    required = {"schema_version", "baseline_id", "runtime_revision", "identity", "public_runtime_contract", "persistence_and_durability", "write_semantics", "read_semantics", "capabilities", "governance_invariants", "qualification_evidence", "known_limitations", "dogfood", "drift_policy"}
    missing = required - set(data)
    if missing:
        raise SystemExit(f"baseline manifest missing required keys: {sorted(missing)}")
    commit = data["runtime_revision"]["commit"]
    if len(commit) != 40 or any(ch not in "0123456789abcdef" for ch in commit):
        raise SystemExit("runtime_revision.commit must be an exact lowercase 40-hex SHA")
    if data["production_1_0"]:
        raise SystemExit("a Runtime Baseline must not claim production 1.0")
    if data["authority_effect"] != "none":
        raise SystemExit("baseline authority_effect must remain none")
    if data["dogfood"].get("required_before_issue_638_close", True) is not True:
        raise SystemExit("public Gauntlet dogfood must remain a close gate")


def render_entry(root: Path, entry: dict) -> tuple[Path, str]:
    record_path = entry["record"]
    data = json.loads((root / record_path).read_text(encoding="utf-8"))
    validate(data)
    public_gauntlet = qualification_block(root, entry)
    output = (root / record_path).with_suffix(".md")
    return output, render(data, public_gauntlet, record_path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--register", type=Path, default=DEFAULT_REGISTER)
    parser.add_argument("--baseline", action="append", default=[], help="baseline_id to render (default: every entry)")
    parser.add_argument("--root", type=Path, default=ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    root = args.root.resolve()
    register = load_register(root, args.register)
    entries = [entry for entry in register["baselines"] if not args.baseline or entry["baseline_id"] in args.baseline]
    if args.baseline and len(entries) != len(set(args.baseline)):
        raise SystemExit(f"unknown baseline id among {args.baseline}")
    for entry in entries:
        output, rendered = render_entry(root, entry)
        if args.check:
            current = output.read_text(encoding="utf-8") if output.exists() else ""
            if current != rendered:
                raise SystemExit(f"{output.relative_to(root)} drifted; run scripts/render_runtime_baseline.py")
            continue
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
